/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * @ssamantle/sdk-typescript
 * FastAPI 기반 백엔드 서비스
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration?: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 정답 추측 요청
 * @export
 * @interface AppApiRoutesSimilarityGuessRequest
 */
export interface AppApiRoutesSimilarityGuessRequest {
    /**
     * 
     * @type {any}
     * @memberof AppApiRoutesSimilarityGuessRequest
     */
    date?: any;
    /**
     * 
     * @type {string}
     * @memberof AppApiRoutesSimilarityGuessRequest
     */
    word: string;
}

/**
 * 정답 추측 응답
 * @export
 * @interface AppApiRoutesSimilarityGuessResponse
 */
export interface AppApiRoutesSimilarityGuessResponse {
    /**
     * 
     * @type {string}
     * @memberof AppApiRoutesSimilarityGuessResponse
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiRoutesSimilarityGuessResponse
     */
    guess: string;
    /**
     * 
     * @type {string}
     * @memberof AppApiRoutesSimilarityGuessResponse
     */
    secretWord: string;
    /**
     * 
     * @type {number}
     * @memberof AppApiRoutesSimilarityGuessResponse
     */
    similarity: number;
}

/**
 * 
 * @export
 * @interface AppSchemasGameGuessRequest
 */
export interface AppSchemasGameGuessRequest {
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGameGuessRequest
     */
    word: string;
}

/**
 * 
 * @export
 * @interface AppSchemasGameGuessResponse
 */
export interface AppSchemasGameGuessResponse {
    /**
     * 
     * @type {number}
     * @memberof AppSchemasGameGuessResponse
     */
    bestSimilarity: number;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGameGuessResponse
     */
    closestWord: string;
    /**
     * 
     * @type {number}
     * @memberof AppSchemasGameGuessResponse
     */
    gameRank: number;
    /**
     * 
     * @type {boolean}
     * @memberof AppSchemasGameGuessResponse
     */
    isCorrect: boolean;
    /**
     * 
     * @type {number}
     * @memberof AppSchemasGameGuessResponse
     */
    similarity: number;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasGameGuessResponse
     */
    word: string;
}

/**
 * 
 * @export
 * @interface CreateGameRequest
 */
export interface CreateGameRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateGameRequest
     */
    endTime?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateGameRequest
     */
    hostname: string;
    /**
     * 
     * @type {any}
     * @memberof CreateGameRequest
     */
    startTime?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateGameRequest
     */
    targetWord: string;
}

/**
 * 
 * @export
 * @interface CreateGameResponse
 */
export interface CreateGameResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateGameResponse
     */
    gameId: number;
}

/**
 * 
 * @export
 * @interface GamePollingResponse
 */
export interface GamePollingResponse {
    /**
     * 
     * @type {string}
     * @memberof GamePollingResponse
     */
    gameStatus: string;
    /**
     * 
     * @type {Array<LeaderboardEntry>}
     * @memberof GamePollingResponse
     */
    leaderboard: Array<LeaderboardEntry>;
    /**
     * 
     * @type {number}
     * @memberof GamePollingResponse
     */
    participationCount: number;
}

/**
 * 
 * @export
 * @interface GameResultResponse
 */
export interface GameResultResponse {
    /**
     * 
     * @type {any}
     * @memberof GameResultResponse
     */
    endedAt: any;
    /**
     * 
     * @type {Array<ParticipantResult>}
     * @memberof GameResultResponse
     */
    participants: Array<ParticipantResult>;
    /**
     * 
     * @type {any}
     * @memberof GameResultResponse
     */
    startedAt: any;
    /**
     * 
     * @type {string}
     * @memberof GameResultResponse
     */
    targetWord: string;
}

/**
 * 
 * @export
 * @interface GameStatusResponse
 */
export interface GameStatusResponse {
    /**
     * 
     * @type {number}
     * @memberof GameStatusResponse
     */
    gameId: number;
    /**
     * 
     * @type {string}
     * @memberof GameStatusResponse
     */
    gameStatus: string;
    /**
     * 
     * @type {number}
     * @memberof GameStatusResponse
     */
    participationCount: number;
}

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    detail?: Array<ValidationError>;
}

/**
 * 
 * @export
 * @interface JoinGameRequest
 */
export interface JoinGameRequest {
    /**
     * 
     * @type {string}
     * @memberof JoinGameRequest
     */
    nickname: string;
}

/**
 * 
 * @export
 * @interface JoinGameResponse
 */
export interface JoinGameResponse {
    /**
     * 
     * @type {number}
     * @memberof JoinGameResponse
     */
    gameId: number;
    /**
     * 
     * @type {string}
     * @memberof JoinGameResponse
     */
    nickname: string;
}

/**
 * 
 * @export
 * @interface LeaderboardEntry
 */
export interface LeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    bestSimilarity: number;
    /**
     * 
     * @type {any}
     * @memberof LeaderboardEntry
     */
    closestWord: any;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    nickname: string;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    rank: number;
}

/**
 * 
 * @export
 * @interface LeaderboardResponse
 */
export interface LeaderboardResponse {
    /**
     * 
     * @type {Array<LeaderboardEntry>}
     * @memberof LeaderboardResponse
     */
    leaderboard: Array<LeaderboardEntry>;
}

/**
 * 
 * @export
 * @interface MessageResponse
 */
export interface MessageResponse {
    /**
     * 
     * @type {string}
     * @memberof MessageResponse
     */
    message: string;
}

/**
 * 
 * @export
 * @interface NicknameCheckResponse
 */
export interface NicknameCheckResponse {
    /**
     * 
     * @type {boolean}
     * @memberof NicknameCheckResponse
     */
    isDuplicate: boolean;
}

/**
 * 
 * @export
 * @interface ParticipantResult
 */
export interface ParticipantResult {
    /**
     * 
     * @type {number}
     * @memberof ParticipantResult
     */
    bestSimilarity: number;
    /**
     * 
     * @type {any}
     * @memberof ParticipantResult
     */
    closestWord: any;
    /**
     * 
     * @type {boolean}
     * @memberof ParticipantResult
     */
    isCorrect: boolean;
    /**
     * 
     * @type {string}
     * @memberof ParticipantResult
     */
    nickname: string;
    /**
     * 
     * @type {number}
     * @memberof ParticipantResult
     */
    rank: number;
}

/**
 * 두 단어 유사도 계산 요청
 * @export
 * @interface SimilarityRequest
 */
export interface SimilarityRequest {
    /**
     * 
     * @type {string}
     * @memberof SimilarityRequest
     */
    word1: string;
    /**
     * 
     * @type {string}
     * @memberof SimilarityRequest
     */
    word2: string;
}

/**
 * 유사도 계산 응답
 * @export
 * @interface SimilarityResponse
 */
export interface SimilarityResponse {
    /**
     * 
     * @type {number}
     * @memberof SimilarityResponse
     */
    similarity: number;
    /**
     * 
     * @type {string}
     * @memberof SimilarityResponse
     */
    word1: string;
    /**
     * 
     * @type {string}
     * @memberof SimilarityResponse
     */
    word2: string;
}

/**
 * 
 * @export
 * @interface UpdateEndtimeRequest
 */
export interface UpdateEndtimeRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateEndtimeRequest
     */
    endedAt?: any;
    /**
     * 
     * @type {any}
     * @memberof UpdateEndtimeRequest
     */
    startedAt?: any;
}

/**
 * 
 * @export
 * @interface UpdateWordRequest
 */
export interface UpdateWordRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWordRequest
     */
    targetWord: string;
}

/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    ctx?: any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    input?: any;
    /**
     * 
     * @type {Array<any>}
     * @memberof ValidationError
     */
    loc: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    type: string;
}


/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options: any = {}): FetchArgs {
            const localVarPath = `/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).rootGet(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: any) {
            return DefaultApiFp(configuration).rootGet(options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: any) {
        return DefaultApiFp(this.configuration).rootGet(options)(this.fetch, this.basePath);
    }

}

/**
 * GamesApi - fetch parameter creator
 * @export
 */
export const GamesApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Game
         * @param {CreateGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGameApiGamesPost(body: CreateGameRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createGameApiGamesPost.');
            }
            const localVarPath = `/api/games`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CreateGameRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary End Game
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endGameApiGamesGameIdEndPost(gameId: number, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling endGameApiGamesGameIdEndPost.');
            }
            const localVarPath = `/api/games/{game_id}/end`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Game Polling
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiGamesGameIdPollingGet(gameId: number, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling gamePollingApiGamesGameIdPollingGet.');
            }
            const localVarPath = `/api/games/{game_id}/polling`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Game Result
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResultApiGamesGameIdResultGet(gameId: number, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling gameResultApiGamesGameIdResultGet.');
            }
            const localVarPath = `/api/games/{game_id}/result`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Game Status
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameStatusApiGamesGameIdStatusGet(gameId: number, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling gameStatusApiGamesGameIdStatusGet.');
            }
            const localVarPath = `/api/games/{game_id}/status`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Guess Word
         * @param {number} gameId 
         * @param {AppSchemasGameGuessRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessWordApiGamesGameIdGuessPost(gameId: number, body: AppSchemasGameGuessRequest, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling guessWordApiGamesGameIdGuessPost.');
            }
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling guessWordApiGamesGameIdGuessPost.');
            }
            const localVarPath = `/api/games/{game_id}/guess`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"AppSchemasGameGuessRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Join Game
         * @param {number} gameId 
         * @param {JoinGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinGameApiGamesGameIdJoinPost(gameId: number, body: JoinGameRequest, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling joinGameApiGamesGameIdJoinPost.');
            }
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling joinGameApiGamesGameIdJoinPost.');
            }
            const localVarPath = `/api/games/{game_id}/join`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JoinGameRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Leaderboard
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaderboardApiGamesGameIdLeaderboardGet(gameId: number, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling leaderboardApiGamesGameIdLeaderboardGet.');
            }
            const localVarPath = `/api/games/{game_id}/leaderboard`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Endtime
         * @param {number} gameId 
         * @param {UpdateEndtimeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEndtimeApiGamesGameIdEndtimePatch(gameId: number, body: UpdateEndtimeRequest, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling updateEndtimeApiGamesGameIdEndtimePatch.');
            }
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateEndtimeApiGamesGameIdEndtimePatch.');
            }
            const localVarPath = `/api/games/{game_id}/endtime`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UpdateEndtimeRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Word
         * @param {number} gameId 
         * @param {UpdateWordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWordApiGamesGameIdWordPatch(gameId: number, body: UpdateWordRequest, options: any = {}): FetchArgs {
            // verify required parameter 'gameId' is not null or undefined
            if (gameId === null || gameId === undefined) {
                throw new RequiredError('gameId','Required parameter gameId was null or undefined when calling updateWordApiGamesGameIdWordPatch.');
            }
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateWordApiGamesGameIdWordPatch.');
            }
            const localVarPath = `/api/games/{game_id}/word`
                .replace(`{${"game_id"}}`, encodeURIComponent(String(gameId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UpdateWordRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GamesApi - functional programming interface
 * @export
 */
export const GamesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Game
         * @param {CreateGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGameApiGamesPost(body: CreateGameRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CreateGameResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).createGameApiGamesPost(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary End Game
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endGameApiGamesGameIdEndPost(gameId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).endGameApiGamesGameIdEndPost(gameId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Game Polling
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiGamesGameIdPollingGet(gameId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GamePollingResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).gamePollingApiGamesGameIdPollingGet(gameId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Game Result
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResultApiGamesGameIdResultGet(gameId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GameResultResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).gameResultApiGamesGameIdResultGet(gameId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Game Status
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameStatusApiGamesGameIdStatusGet(gameId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GameStatusResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).gameStatusApiGamesGameIdStatusGet(gameId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Guess Word
         * @param {number} gameId 
         * @param {AppSchemasGameGuessRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessWordApiGamesGameIdGuessPost(gameId: number, body: AppSchemasGameGuessRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AppSchemasGameGuessResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).guessWordApiGamesGameIdGuessPost(gameId, body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Join Game
         * @param {number} gameId 
         * @param {JoinGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinGameApiGamesGameIdJoinPost(gameId: number, body: JoinGameRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JoinGameResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).joinGameApiGamesGameIdJoinPost(gameId, body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Leaderboard
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaderboardApiGamesGameIdLeaderboardGet(gameId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<LeaderboardResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).leaderboardApiGamesGameIdLeaderboardGet(gameId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update Endtime
         * @param {number} gameId 
         * @param {UpdateEndtimeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEndtimeApiGamesGameIdEndtimePatch(gameId: number, body: UpdateEndtimeRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).updateEndtimeApiGamesGameIdEndtimePatch(gameId, body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update Word
         * @param {number} gameId 
         * @param {UpdateWordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWordApiGamesGameIdWordPatch(gameId: number, body: UpdateWordRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageResponse> {
            const localVarFetchArgs = GamesApiFetchParamCreator(configuration).updateWordApiGamesGameIdWordPatch(gameId, body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * GamesApi - factory interface
 * @export
 */
export const GamesApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Create Game
         * @param {CreateGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGameApiGamesPost(body: CreateGameRequest, options?: any) {
            return GamesApiFp(configuration).createGameApiGamesPost(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary End Game
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endGameApiGamesGameIdEndPost(gameId: number, options?: any) {
            return GamesApiFp(configuration).endGameApiGamesGameIdEndPost(gameId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Game Polling
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiGamesGameIdPollingGet(gameId: number, options?: any) {
            return GamesApiFp(configuration).gamePollingApiGamesGameIdPollingGet(gameId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Game Result
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResultApiGamesGameIdResultGet(gameId: number, options?: any) {
            return GamesApiFp(configuration).gameResultApiGamesGameIdResultGet(gameId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Game Status
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameStatusApiGamesGameIdStatusGet(gameId: number, options?: any) {
            return GamesApiFp(configuration).gameStatusApiGamesGameIdStatusGet(gameId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Guess Word
         * @param {number} gameId 
         * @param {AppSchemasGameGuessRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessWordApiGamesGameIdGuessPost(gameId: number, body: AppSchemasGameGuessRequest, options?: any) {
            return GamesApiFp(configuration).guessWordApiGamesGameIdGuessPost(gameId, body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Join Game
         * @param {number} gameId 
         * @param {JoinGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinGameApiGamesGameIdJoinPost(gameId: number, body: JoinGameRequest, options?: any) {
            return GamesApiFp(configuration).joinGameApiGamesGameIdJoinPost(gameId, body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Leaderboard
         * @param {number} gameId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaderboardApiGamesGameIdLeaderboardGet(gameId: number, options?: any) {
            return GamesApiFp(configuration).leaderboardApiGamesGameIdLeaderboardGet(gameId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update Endtime
         * @param {number} gameId 
         * @param {UpdateEndtimeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEndtimeApiGamesGameIdEndtimePatch(gameId: number, body: UpdateEndtimeRequest, options?: any) {
            return GamesApiFp(configuration).updateEndtimeApiGamesGameIdEndtimePatch(gameId, body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update Word
         * @param {number} gameId 
         * @param {UpdateWordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWordApiGamesGameIdWordPatch(gameId: number, body: UpdateWordRequest, options?: any) {
            return GamesApiFp(configuration).updateWordApiGamesGameIdWordPatch(gameId, body, options)(fetch, basePath);
        },
    };
};

/**
 * GamesApi - object-oriented interface
 * @export
 * @class GamesApi
 * @extends {BaseAPI}
 */
export class GamesApi extends BaseAPI {
    /**
     * 
     * @summary Create Game
     * @param {CreateGameRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public createGameApiGamesPost(body: CreateGameRequest, options?: any) {
        return GamesApiFp(this.configuration).createGameApiGamesPost(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary End Game
     * @param {number} gameId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public endGameApiGamesGameIdEndPost(gameId: number, options?: any) {
        return GamesApiFp(this.configuration).endGameApiGamesGameIdEndPost(gameId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Game Polling
     * @param {number} gameId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public gamePollingApiGamesGameIdPollingGet(gameId: number, options?: any) {
        return GamesApiFp(this.configuration).gamePollingApiGamesGameIdPollingGet(gameId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Game Result
     * @param {number} gameId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public gameResultApiGamesGameIdResultGet(gameId: number, options?: any) {
        return GamesApiFp(this.configuration).gameResultApiGamesGameIdResultGet(gameId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Game Status
     * @param {number} gameId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public gameStatusApiGamesGameIdStatusGet(gameId: number, options?: any) {
        return GamesApiFp(this.configuration).gameStatusApiGamesGameIdStatusGet(gameId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Guess Word
     * @param {number} gameId 
     * @param {AppSchemasGameGuessRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public guessWordApiGamesGameIdGuessPost(gameId: number, body: AppSchemasGameGuessRequest, options?: any) {
        return GamesApiFp(this.configuration).guessWordApiGamesGameIdGuessPost(gameId, body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Join Game
     * @param {number} gameId 
     * @param {JoinGameRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public joinGameApiGamesGameIdJoinPost(gameId: number, body: JoinGameRequest, options?: any) {
        return GamesApiFp(this.configuration).joinGameApiGamesGameIdJoinPost(gameId, body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Leaderboard
     * @param {number} gameId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public leaderboardApiGamesGameIdLeaderboardGet(gameId: number, options?: any) {
        return GamesApiFp(this.configuration).leaderboardApiGamesGameIdLeaderboardGet(gameId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update Endtime
     * @param {number} gameId 
     * @param {UpdateEndtimeRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public updateEndtimeApiGamesGameIdEndtimePatch(gameId: number, body: UpdateEndtimeRequest, options?: any) {
        return GamesApiFp(this.configuration).updateEndtimeApiGamesGameIdEndtimePatch(gameId, body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update Word
     * @param {number} gameId 
     * @param {UpdateWordRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesApi
     */
    public updateWordApiGamesGameIdWordPatch(gameId: number, body: UpdateWordRequest, options?: any) {
        return GamesApiFp(this.configuration).updateWordApiGamesGameIdWordPatch(gameId, body, options)(this.fetch, this.basePath);
    }

}

/**
 * HealthApi - fetch parameter creator
 * @export
 */
export const HealthApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 헬스 체크
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options: any = {}): FetchArgs {
            const localVarPath = `/health`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 헬스 체크
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = HealthApiFetchParamCreator(configuration).healthCheckHealthGet(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 헬스 체크
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: any) {
            return HealthApiFp(configuration).healthCheckHealthGet(options)(fetch, basePath);
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * 헬스 체크
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthCheckHealthGet(options?: any) {
        return HealthApiFp(this.configuration).healthCheckHealthGet(options)(this.fetch, this.basePath);
    }

}

/**
 * SimilarityApi - fetch parameter creator
 * @export
 */
export const SimilarityApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 두 단어의 유사도를 계산합니다.
         * @summary Calculate Similarity
         * @param {SimilarityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateSimilarityApiSimilarityPost(body: SimilarityRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling calculateSimilarityApiSimilarityPost.');
            }
            const localVarPath = `/api/similarity/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"SimilarityRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 정답 단어를 추측합니다.
         * @summary Guess Secret Word
         * @param {AppApiRoutesSimilarityGuessRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessSecretWordApiSimilarityGuessPost(body: AppApiRoutesSimilarityGuessRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling guessSecretWordApiSimilarityGuessPost.');
            }
            const localVarPath = `/api/similarity/guess`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"AppApiRoutesSimilarityGuessRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SimilarityApi - functional programming interface
 * @export
 */
export const SimilarityApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 두 단어의 유사도를 계산합니다.
         * @summary Calculate Similarity
         * @param {SimilarityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateSimilarityApiSimilarityPost(body: SimilarityRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<SimilarityResponse> {
            const localVarFetchArgs = SimilarityApiFetchParamCreator(configuration).calculateSimilarityApiSimilarityPost(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 정답 단어를 추측합니다.
         * @summary Guess Secret Word
         * @param {AppApiRoutesSimilarityGuessRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessSecretWordApiSimilarityGuessPost(body: AppApiRoutesSimilarityGuessRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AppApiRoutesSimilarityGuessResponse> {
            const localVarFetchArgs = SimilarityApiFetchParamCreator(configuration).guessSecretWordApiSimilarityGuessPost(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * SimilarityApi - factory interface
 * @export
 */
export const SimilarityApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 두 단어의 유사도를 계산합니다.
         * @summary Calculate Similarity
         * @param {SimilarityRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateSimilarityApiSimilarityPost(body: SimilarityRequest, options?: any) {
            return SimilarityApiFp(configuration).calculateSimilarityApiSimilarityPost(body, options)(fetch, basePath);
        },
        /**
         * 정답 단어를 추측합니다.
         * @summary Guess Secret Word
         * @param {AppApiRoutesSimilarityGuessRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessSecretWordApiSimilarityGuessPost(body: AppApiRoutesSimilarityGuessRequest, options?: any) {
            return SimilarityApiFp(configuration).guessSecretWordApiSimilarityGuessPost(body, options)(fetch, basePath);
        },
    };
};

/**
 * SimilarityApi - object-oriented interface
 * @export
 * @class SimilarityApi
 * @extends {BaseAPI}
 */
export class SimilarityApi extends BaseAPI {
    /**
     * 두 단어의 유사도를 계산합니다.
     * @summary Calculate Similarity
     * @param {SimilarityRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimilarityApi
     */
    public calculateSimilarityApiSimilarityPost(body: SimilarityRequest, options?: any) {
        return SimilarityApiFp(this.configuration).calculateSimilarityApiSimilarityPost(body, options)(this.fetch, this.basePath);
    }

    /**
     * 정답 단어를 추측합니다.
     * @summary Guess Secret Word
     * @param {AppApiRoutesSimilarityGuessRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SimilarityApi
     */
    public guessSecretWordApiSimilarityGuessPost(body: AppApiRoutesSimilarityGuessRequest, options?: any) {
        return SimilarityApiFp(this.configuration).guessSecretWordApiSimilarityGuessPost(body, options)(this.fetch, this.basePath);
    }

}

/**
 * UsersApi - fetch parameter creator
 * @export
 */
export const UsersApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 닉네임 중복 확인 — 진행 중인 게임(WAITING/ACTIVE) 기준
         * @summary Check Nickname
         * @param {string} nickname 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNicknameApiUsersCheckNicknameGet(nickname: string, options: any = {}): FetchArgs {
            // verify required parameter 'nickname' is not null or undefined
            if (nickname === null || nickname === undefined) {
                throw new RequiredError('nickname','Required parameter nickname was null or undefined when calling checkNicknameApiUsersCheckNicknameGet.');
            }
            const localVarPath = `/api/users/check-nickname`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nickname !== undefined) {
                localVarQueryParameter['nickname'] = nickname;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 닉네임 중복 확인 — 진행 중인 게임(WAITING/ACTIVE) 기준
         * @summary Check Nickname
         * @param {string} nickname 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNicknameApiUsersCheckNicknameGet(nickname: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<NicknameCheckResponse> {
            const localVarFetchArgs = UsersApiFetchParamCreator(configuration).checkNicknameApiUsersCheckNicknameGet(nickname, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 닉네임 중복 확인 — 진행 중인 게임(WAITING/ACTIVE) 기준
         * @summary Check Nickname
         * @param {string} nickname 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNicknameApiUsersCheckNicknameGet(nickname: string, options?: any) {
            return UsersApiFp(configuration).checkNicknameApiUsersCheckNicknameGet(nickname, options)(fetch, basePath);
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 닉네임 중복 확인 — 진행 중인 게임(WAITING/ACTIVE) 기준
     * @summary Check Nickname
     * @param {string} nickname 확인할 닉네임
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public checkNicknameApiUsersCheckNicknameGet(nickname: string, options?: any) {
        return UsersApiFp(this.configuration).checkNicknameApiUsersCheckNicknameGet(nickname, options)(this.fetch, this.basePath);
    }

}

