/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Semantle Server
 * FastAPI 기반 백엔드 서비스
 *
 * OpenAPI spec version: 0.0.4
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface CreateGameRequest
 */
export interface CreateGameRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateGameRequest
     */
    hostname: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGameRequest
     */
    targetWord: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGameRequest
     */
    startTime?: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGameRequest
     */
    endTime?: any;
}
/**
 * 
 * @export
 * @interface CreateGameResponse
 */
export interface CreateGameResponse {
    /**
     * 
     * @type {any}
     * @memberof CreateGameResponse
     */
    gameId: any;
    /**
     * 
     * @type {any}
     * @memberof CreateGameResponse
     */
    sessionId: any;
}
/**
 * 
 * @export
 * @interface GameInfoResponse
 */
export interface GameInfoResponse {
    /**
     * 
     * @type {any}
     * @memberof GameInfoResponse
     */
    startAt: any;
    /**
     * 
     * @type {any}
     * @memberof GameInfoResponse
     */
    endAt: any;
    /**
     * 
     * @type {any}
     * @memberof GameInfoResponse
     */
    users: any;
}
/**
 * 
 * @export
 * @interface GameResultResponse
 */
export interface GameResultResponse {
    /**
     * 
     * @type {any}
     * @memberof GameResultResponse
     */
    targetWord: any;
    /**
     * 
     * @type {any}
     * @memberof GameResultResponse
     */
    startedAt: any;
    /**
     * 
     * @type {any}
     * @memberof GameResultResponse
     */
    endedAt: any;
    /**
     * 
     * @type {any}
     * @memberof GameResultResponse
     */
    participants: any;
}
/**
 * 
 * @export
 * @interface GuessHistoryItem
 */
export interface GuessHistoryItem {
    /**
     * 
     * @type {any}
     * @memberof GuessHistoryItem
     */
    label: any;
    /**
     * 
     * @type {any}
     * @memberof GuessHistoryItem
     */
    similarity: any;
    /**
     * 
     * @type {any}
     * @memberof GuessHistoryItem
     */
    rank: any;
    /**
     * 
     * @type {any}
     * @memberof GuessHistoryItem
     */
    wordRank: any;
    /**
     * 
     * @type {any}
     * @memberof GuessHistoryItem
     */
    isAnswer: any;
}
/**
 * 
 * @export
 * @interface GuessRequest
 */
export interface GuessRequest {
    /**
     * 
     * @type {any}
     * @memberof GuessRequest
     */
    username: any;
    /**
     * 
     * @type {any}
     * @memberof GuessRequest
     */
    word: any;
}
/**
 * 
 * @export
 * @interface GuessResponse
 */
export interface GuessResponse {
    /**
     * 
     * @type {any}
     * @memberof GuessResponse
     */
    label: any;
    /**
     * 
     * @type {any}
     * @memberof GuessResponse
     */
    similarity: any;
    /**
     * 
     * @type {any}
     * @memberof GuessResponse
     */
    rank: any;
    /**
     * 
     * @type {any}
     * @memberof GuessResponse
     */
    wordRank: any;
    /**
     * 
     * @type {any}
     * @memberof GuessResponse
     */
    isAnswer: any;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {any}
     * @memberof HTTPValidationError
     */
    detail?: any;
}
/**
 * 
 * @export
 * @interface JoinGameRequest
 */
export interface JoinGameRequest {
    /**
     * 
     * @type {any}
     * @memberof JoinGameRequest
     */
    nickname: any;
}
/**
 * 
 * @export
 * @interface JoinGameResponse
 */
export interface JoinGameResponse {
    /**
     * 
     * @type {any}
     * @memberof JoinGameResponse
     */
    gameId: any;
    /**
     * 
     * @type {any}
     * @memberof JoinGameResponse
     */
    nickname: any;
    /**
     * 
     * @type {any}
     * @memberof JoinGameResponse
     */
    sessionId: any;
}
/**
 * 
 * @export
 * @interface MessageResponse
 */
export interface MessageResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageResponse
     */
    message: any;
}
/**
 * 
 * @export
 * @interface NicknameCheckResponse
 */
export interface NicknameCheckResponse {
    /**
     * 
     * @type {any}
     * @memberof NicknameCheckResponse
     */
    isDuplicate: any;
}
/**
 * 
 * @export
 * @interface ParticipantResult
 */
export interface ParticipantResult {
    /**
     * 
     * @type {any}
     * @memberof ParticipantResult
     */
    rank: any;
    /**
     * 
     * @type {any}
     * @memberof ParticipantResult
     */
    nickname: any;
    /**
     * 
     * @type {any}
     * @memberof ParticipantResult
     */
    bestSimilarity: any;
    /**
     * 
     * @type {any}
     * @memberof ParticipantResult
     */
    closestWord: any;
    /**
     * 
     * @type {any}
     * @memberof ParticipantResult
     */
    isCorrect: any;
}
/**
 * 
 * @export
 * @interface SubmissionSummary
 */
export interface SubmissionSummary {
    /**
     * 
     * @type {any}
     * @memberof SubmissionSummary
     */
    similarity: any;
    /**
     * 
     * @type {any}
     * @memberof SubmissionSummary
     */
    wordRank: any;
}
/**
 * 
 * @export
 * @interface UpdateEndtimeRequest
 */
export interface UpdateEndtimeRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateEndtimeRequest
     */
    startedAt?: any;
    /**
     * 
     * @type {any}
     * @memberof UpdateEndtimeRequest
     */
    endedAt?: any;
}
/**
 * 
 * @export
 * @interface UpdateWordRequest
 */
export interface UpdateWordRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateWordRequest
     */
    targetWord: any;
}
/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {any}
     * @memberof UserInfo
     */
    name: any;
    /**
     * 
     * @type {any}
     * @memberof UserInfo
     */
    bestSimilarity: any;
    /**
     * 
     * @type {any}
     * @memberof UserInfo
     */
    rank: any;
    /**
     * 
     * @type {any}
     * @memberof UserInfo
     */
    bestSubmission?: any;
    /**
     * 
     * @type {any}
     * @memberof UserInfo
     */
    latestSubmission?: any;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    loc: any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    msg: any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    type: any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    input?: any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    ctx?: any;
}
/**
 * AuthApi - fetch parameter creator
 * @export
 */
export const AuthApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 세션ID(토큰) 유효성 검사
         * @summary Validate Token
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateTokenAuthValidateGet(authorization: any, options: any = {}): FetchArgs {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling validateTokenAuthValidateGet.');
            }
            const localVarPath = `/auth/validate`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 세션ID(토큰) 유효성 검사
         * @summary Validate Token
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateTokenAuthValidateGet(authorization: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = AuthApiFetchParamCreator(configuration).validateTokenAuthValidateGet(authorization, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 세션ID(토큰) 유효성 검사
         * @summary Validate Token
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateTokenAuthValidateGet(authorization: any, options?: any) {
            return AuthApiFp(configuration).validateTokenAuthValidateGet(authorization, options)(fetch, basePath);
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 세션ID(토큰) 유효성 검사
     * @summary Validate Token
     * @param {any} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public validateTokenAuthValidateGet(authorization: any, options?: any) {
        return AuthApiFp(this.configuration).validateTokenAuthValidateGet(authorization, options)(this.fetch, this.basePath);
    }

}
/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options: any = {}): FetchArgs {
            const localVarPath = `/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).rootGet(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Root
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options?: any) {
            return DefaultApiFp(configuration).rootGet(options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Root
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public rootGet(options?: any) {
        return DefaultApiFp(this.configuration).rootGet(options)(this.fetch, this.basePath);
    }

}
/**
 * GamesV1Api - fetch parameter creator
 * @export
 */
export const GamesV1ApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Game
         * @param {CreateGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGameApiV1GamesPost(body: CreateGameRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createGameApiV1GamesPost.');
            }
            const localVarPath = `/api/v1/games`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CreateGameRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary End Game
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endGameApiV1GamesEndPost(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/games/end`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Game Polling
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiV1GamesPollingDbGet(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/games/polling/db`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Game Polling
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiV1GamesPollingGet(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/games/polling`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Game Result
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResultApiV1GamesResultGet(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/games/result`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Guess History
         * @param {any} username 
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGuessHistoryApiV1GamesGuessesGet(username: any, authorization: any, options: any = {}): FetchArgs {
            // verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling getGuessHistoryApiV1GamesGuessesGet.');
            }
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getGuessHistoryApiV1GamesGuessesGet.');
            }
            const localVarPath = `/api/v1/games/guesses`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Guess Word
         * @param {GuessRequest} body 
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessWordApiV1GamesGuessPost(body: GuessRequest, authorization: any, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling guessWordApiV1GamesGuessPost.');
            }
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling guessWordApiV1GamesGuessPost.');
            }
            const localVarPath = `/api/v1/games/guess`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['authorization'] = String(authorization);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"GuessRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Join Game
         * @param {JoinGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinGameApiV1GamesJoinPost(body: JoinGameRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling joinGameApiV1GamesJoinPost.');
            }
            const localVarPath = `/api/v1/games/join`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JoinGameRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Endtime
         * @param {UpdateEndtimeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEndtimeApiV1GamesTimePatch(body: UpdateEndtimeRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateEndtimeApiV1GamesTimePatch.');
            }
            const localVarPath = `/api/v1/games/time`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UpdateEndtimeRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Word
         * @param {UpdateWordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWordApiV1GamesWordPatch(body: UpdateWordRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateWordApiV1GamesWordPatch.');
            }
            const localVarPath = `/api/v1/games/word`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UpdateWordRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GamesV1Api - functional programming interface
 * @export
 */
export const GamesV1ApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Game
         * @param {CreateGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGameApiV1GamesPost(body: CreateGameRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CreateGameResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).createGameApiV1GamesPost(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary End Game
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endGameApiV1GamesEndPost(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).endGameApiV1GamesEndPost(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Game Polling
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiV1GamesPollingDbGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GameInfoResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).gamePollingApiV1GamesPollingDbGet(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Game Polling
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiV1GamesPollingGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GameInfoResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).gamePollingApiV1GamesPollingGet(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Game Result
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResultApiV1GamesResultGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GameResultResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).gameResultApiV1GamesResultGet(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Get Guess History
         * @param {any} username 
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGuessHistoryApiV1GamesGuessesGet(username: any, authorization: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).getGuessHistoryApiV1GamesGuessesGet(username, authorization, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Guess Word
         * @param {GuessRequest} body 
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessWordApiV1GamesGuessPost(body: GuessRequest, authorization: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GuessResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).guessWordApiV1GamesGuessPost(body, authorization, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Join Game
         * @param {JoinGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinGameApiV1GamesJoinPost(body: JoinGameRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JoinGameResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).joinGameApiV1GamesJoinPost(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update Endtime
         * @param {UpdateEndtimeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEndtimeApiV1GamesTimePatch(body: UpdateEndtimeRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).updateEndtimeApiV1GamesTimePatch(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update Word
         * @param {UpdateWordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWordApiV1GamesWordPatch(body: UpdateWordRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MessageResponse> {
            const localVarFetchArgs = GamesV1ApiFetchParamCreator(configuration).updateWordApiV1GamesWordPatch(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * GamesV1Api - factory interface
 * @export
 */
export const GamesV1ApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Create Game
         * @param {CreateGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGameApiV1GamesPost(body: CreateGameRequest, options?: any) {
            return GamesV1ApiFp(configuration).createGameApiV1GamesPost(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary End Game
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        endGameApiV1GamesEndPost(options?: any) {
            return GamesV1ApiFp(configuration).endGameApiV1GamesEndPost(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Game Polling
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiV1GamesPollingDbGet(options?: any) {
            return GamesV1ApiFp(configuration).gamePollingApiV1GamesPollingDbGet(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Game Polling
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamePollingApiV1GamesPollingGet(options?: any) {
            return GamesV1ApiFp(configuration).gamePollingApiV1GamesPollingGet(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Game Result
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gameResultApiV1GamesResultGet(options?: any) {
            return GamesV1ApiFp(configuration).gameResultApiV1GamesResultGet(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Get Guess History
         * @param {any} username 
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGuessHistoryApiV1GamesGuessesGet(username: any, authorization: any, options?: any) {
            return GamesV1ApiFp(configuration).getGuessHistoryApiV1GamesGuessesGet(username, authorization, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Guess Word
         * @param {GuessRequest} body 
         * @param {any} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessWordApiV1GamesGuessPost(body: GuessRequest, authorization: any, options?: any) {
            return GamesV1ApiFp(configuration).guessWordApiV1GamesGuessPost(body, authorization, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Join Game
         * @param {JoinGameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        joinGameApiV1GamesJoinPost(body: JoinGameRequest, options?: any) {
            return GamesV1ApiFp(configuration).joinGameApiV1GamesJoinPost(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update Endtime
         * @param {UpdateEndtimeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEndtimeApiV1GamesTimePatch(body: UpdateEndtimeRequest, options?: any) {
            return GamesV1ApiFp(configuration).updateEndtimeApiV1GamesTimePatch(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update Word
         * @param {UpdateWordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWordApiV1GamesWordPatch(body: UpdateWordRequest, options?: any) {
            return GamesV1ApiFp(configuration).updateWordApiV1GamesWordPatch(body, options)(fetch, basePath);
        },
    };
};

/**
 * GamesV1Api - object-oriented interface
 * @export
 * @class GamesV1Api
 * @extends {BaseAPI}
 */
export class GamesV1Api extends BaseAPI {
    /**
     * 
     * @summary Create Game
     * @param {CreateGameRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public createGameApiV1GamesPost(body: CreateGameRequest, options?: any) {
        return GamesV1ApiFp(this.configuration).createGameApiV1GamesPost(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary End Game
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public endGameApiV1GamesEndPost(options?: any) {
        return GamesV1ApiFp(this.configuration).endGameApiV1GamesEndPost(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Game Polling
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public gamePollingApiV1GamesPollingDbGet(options?: any) {
        return GamesV1ApiFp(this.configuration).gamePollingApiV1GamesPollingDbGet(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Game Polling
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public gamePollingApiV1GamesPollingGet(options?: any) {
        return GamesV1ApiFp(this.configuration).gamePollingApiV1GamesPollingGet(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Game Result
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public gameResultApiV1GamesResultGet(options?: any) {
        return GamesV1ApiFp(this.configuration).gameResultApiV1GamesResultGet(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Get Guess History
     * @param {any} username 
     * @param {any} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public getGuessHistoryApiV1GamesGuessesGet(username: any, authorization: any, options?: any) {
        return GamesV1ApiFp(this.configuration).getGuessHistoryApiV1GamesGuessesGet(username, authorization, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Guess Word
     * @param {GuessRequest} body 
     * @param {any} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public guessWordApiV1GamesGuessPost(body: GuessRequest, authorization: any, options?: any) {
        return GamesV1ApiFp(this.configuration).guessWordApiV1GamesGuessPost(body, authorization, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Join Game
     * @param {JoinGameRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public joinGameApiV1GamesJoinPost(body: JoinGameRequest, options?: any) {
        return GamesV1ApiFp(this.configuration).joinGameApiV1GamesJoinPost(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update Endtime
     * @param {UpdateEndtimeRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public updateEndtimeApiV1GamesTimePatch(body: UpdateEndtimeRequest, options?: any) {
        return GamesV1ApiFp(this.configuration).updateEndtimeApiV1GamesTimePatch(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update Word
     * @param {UpdateWordRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamesV1Api
     */
    public updateWordApiV1GamesWordPatch(body: UpdateWordRequest, options?: any) {
        return GamesV1ApiFp(this.configuration).updateWordApiV1GamesWordPatch(body, options)(this.fetch, this.basePath);
    }

}
/**
 * HealthApi - fetch parameter creator
 * @export
 */
export const HealthApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 헬스 체크
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options: any = {}): FetchArgs {
            const localVarPath = `/health`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 헬스 체크
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = HealthApiFetchParamCreator(configuration).healthCheckHealthGet(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 헬스 체크
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: any) {
            return HealthApiFp(configuration).healthCheckHealthGet(options)(fetch, basePath);
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * 헬스 체크
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthCheckHealthGet(options?: any) {
        return HealthApiFp(this.configuration).healthCheckHealthGet(options)(this.fetch, this.basePath);
    }

}
/**
 * UsersApi - fetch parameter creator
 * @export
 */
export const UsersApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 닉네임 중복 확인 — 진행 중인 게임(PREGAME/INGAME) 기준
         * @summary Check Nickname
         * @param {any} nickname 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNicknameApiUsersCheckNicknameGet(nickname: any, options: any = {}): FetchArgs {
            // verify required parameter 'nickname' is not null or undefined
            if (nickname === null || nickname === undefined) {
                throw new RequiredError('nickname','Required parameter nickname was null or undefined when calling checkNicknameApiUsersCheckNicknameGet.');
            }
            const localVarPath = `/api/users/check-nickname`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nickname !== undefined) {
                localVarQueryParameter['nickname'] = nickname;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 닉네임 중복 확인 — 진행 중인 게임(PREGAME/INGAME) 기준
         * @summary Check Nickname
         * @param {any} nickname 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNicknameApiUsersCheckNicknameGet(nickname: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<NicknameCheckResponse> {
            const localVarFetchArgs = UsersApiFetchParamCreator(configuration).checkNicknameApiUsersCheckNicknameGet(nickname, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 닉네임 중복 확인 — 진행 중인 게임(PREGAME/INGAME) 기준
         * @summary Check Nickname
         * @param {any} nickname 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNicknameApiUsersCheckNicknameGet(nickname: any, options?: any) {
            return UsersApiFp(configuration).checkNicknameApiUsersCheckNicknameGet(nickname, options)(fetch, basePath);
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 닉네임 중복 확인 — 진행 중인 게임(PREGAME/INGAME) 기준
     * @summary Check Nickname
     * @param {any} nickname 확인할 닉네임
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public checkNicknameApiUsersCheckNicknameGet(nickname: any, options?: any) {
        return UsersApiFp(this.configuration).checkNicknameApiUsersCheckNicknameGet(nickname, options)(this.fetch, this.basePath);
    }

}
