/**
 * Semantle Server
 * FastAPI 기반 백엔드 서비스
 *
 * OpenAPI spec version: 0.0.4
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AuthApi", () => {
  let instance: api.AuthApi
  beforeEach(function() {
    instance = new api.AuthApi(config)
  });

  test("validateTokenAuthValidateGet", () => {
    const authorization: any = undefined
    return expect(instance.validateTokenAuthValidateGet(authorization, {})).resolves.toBe(null)
  })
})

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("rootGet", () => {
    return expect(instance.rootGet({})).resolves.toBe(null)
  })
})

describe("GamesV1Api", () => {
  let instance: api.GamesV1Api
  beforeEach(function() {
    instance = new api.GamesV1Api(config)
  });

  test("createGameApiV1GamesPost", () => {
    const body: api.CreateGameRequest = undefined
    return expect(instance.createGameApiV1GamesPost(body, {})).resolves.toBe(null)
  })
  test("endGameApiV1GamesEndPost", () => {
    return expect(instance.endGameApiV1GamesEndPost({})).resolves.toBe(null)
  })
  test("gamePollingApiV1GamesPollingDbGet", () => {
    return expect(instance.gamePollingApiV1GamesPollingDbGet({})).resolves.toBe(null)
  })
  test("gamePollingApiV1GamesPollingGet", () => {
    return expect(instance.gamePollingApiV1GamesPollingGet({})).resolves.toBe(null)
  })
  test("gameResultApiV1GamesResultGet", () => {
    return expect(instance.gameResultApiV1GamesResultGet({})).resolves.toBe(null)
  })
  test("getGuessHistoryApiV1GamesGuessesGet", () => {
    const username: any = undefined
    const authorization: any = undefined
    return expect(instance.getGuessHistoryApiV1GamesGuessesGet(username, authorization, {})).resolves.toBe(null)
  })
  test("guessWordApiV1GamesGuessPost", () => {
    const body: api.GuessRequest = undefined
    const authorization: any = undefined
    return expect(instance.guessWordApiV1GamesGuessPost(body, authorization, {})).resolves.toBe(null)
  })
  test("joinGameApiV1GamesJoinPost", () => {
    const body: api.JoinGameRequest = undefined
    return expect(instance.joinGameApiV1GamesJoinPost(body, {})).resolves.toBe(null)
  })
  test("updateEndtimeApiV1GamesTimePatch", () => {
    const body: api.UpdateEndtimeRequest = undefined
    return expect(instance.updateEndtimeApiV1GamesTimePatch(body, {})).resolves.toBe(null)
  })
  test("updateWordApiV1GamesWordPatch", () => {
    const body: api.UpdateWordRequest = undefined
    return expect(instance.updateWordApiV1GamesWordPatch(body, {})).resolves.toBe(null)
  })
})

describe("HealthApi", () => {
  let instance: api.HealthApi
  beforeEach(function() {
    instance = new api.HealthApi(config)
  });

  test("healthCheckHealthGet", () => {
    return expect(instance.healthCheckHealthGet({})).resolves.toBe(null)
  })
})

describe("UsersApi", () => {
  let instance: api.UsersApi
  beforeEach(function() {
    instance = new api.UsersApi(config)
  });

  test("checkNicknameApiUsersCheckNicknameGet", () => {
    const nickname: any = undefined
    return expect(instance.checkNicknameApiUsersCheckNicknameGet(nickname, {})).resolves.toBe(null)
  })
})

